config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Devise 認証用のルート
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  namespace :api do
    resources :timelines
    resources :users, only: [:show] do
      resource :profile, only: %i[show edit update], controller: 'profiles'
    end

    post 'favorites/:id', to: 'favorites#create', as: 'add_to_favorites'
    delete 'favorites/:id', to: 'favorites#destroy', as: 'destroy_favorite'

    # ログイン状態確認API
    resource :session, only: [:show]
  end

  # ✅ ルート画面（ログイン状態であれば api/timelines#index、未ログインなら sign_in にリダイレクトされる）
  root 'api/timelines#index'
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update]
  before_action :set_user

  def show
    @timelines = @user.timelines.order(created_at: :desc)
  end

  def edit; end

  def update
    # パスワードのバリデーションをスキップするフラグを設定
    @user.skip_password_validation = true
    if @user.update(profile_params)
      redirect_to user_profile_path(@user), notice: 'プロフィールが更新されました。'
    else
      render :edit
    end
  end

  private

  # ユーザーをセットするメソッド
  def set_user
    @user = User.find(params[:user_id])
  end

  # プロフィールのパラメータを許可するメソッド
  def profile_params
    params.require(:user).permit(:name, :bio)
  end
end

app/views/profiles/edit.html.erb
<h1>プロフィール編集</h1>

<%= form_with(model: @user, url: user_profile_path(@user), method: :put, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "エラー") %>が発生しました:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, '名前' %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :bio, '自己紹介' %>
    <%= form.text_area :bio %>
  </div>
  <div>
    <%= form.submit '更新' %>
  </div>
<% end %>

<%= link_to 'キャンセル', user_profile_path(@user) %>

app/views/profiles/show.html.erb
<div>
  <h1><%= @user.name %></h1>
  <p><%= @user.beebits_name %></p>
  <p><%= @user.bio %></p>
  <p><%= t('profiles.using_since', year: @user.created_at.year, month: @user.created_at.month) %></p>
  <% if @user == current_user %>
    <%= link_to 'プロフィールを編集', edit_user_profile_path(@user) %>
  <% end %>
</div>

<div class="user-posts">
  <% @timelines.each do |timeline| %>
    <%= render 'timelines/timeline', timeline: timeline %>
  <% end %>
</div>

<%= link_to 'タイムラインへ戻る', timelines_path %>